apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer
  selector:
    app.kubernetes.io/name : grafana